#!/bin/bash

function create() {
    cd /Users/ato/scripts/python_code/ProjectGithubAutomation/
    source .env
    python create.py $1
    cd $FILEPATH$1
    git init
    git remote add origin https://github.com/$USERNAME/$1.git
    touch README.md
    git add .
    git commit -m "Initial commit"
    gita push -u origin master
    code .
}